import type { Metadata } from "next";
import Link from 'next/link'
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import { Navigation } from "../components/Navigation";
//import styles from './layout.module.css'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Providers>
          <header>
            <nav>
              <ul>
                <li><Link href="/">Home</Link></li>
                <li><Link href="/search">Search</Link></li>
                {/* Add more navigation items as needed */}
              </ul>
            </nav>
          </header>
        <main>
          <Navigation />
          {children}
        </main>
        </Providers>
      </body>
    </html>
  );
}
